package(default_visibility = ["//visibility:public"])

filegroup(
    name = "example_configs",
    srcs = glob(["*.yml"]),
    visibility = ["//visibility:public"],
)

filegroup(
    name = "example_properties",
    srcs = ["logback.xml"],
    visibility = ["//visibility:public"],
)
